[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[healthcheck]
path = "/"
timeout = 30
interval = 10
