// 1200+ SEO Anahtar Kelime Listesi - Okan Demir
export const seoKeywords = {
  primary: [
    'Okan Demir',
    'Okan',
    'Demir',
    'Okan Demir kimdir',
    'Okan Demir dijital pazarlama',
    'Okan Demir yazılım',
    'Okan Demir web tasarım',
    'O Copyright Dijital Pazarlama',
    'O Copyright Yazılım',
  ],
  
  digitalMarketing: [
    'dijital pazarlama',
    'dijital pazarlama uzmanı',
    'dijital pazarlama danışmanı',
    'dijital pazarlama ajansı',
    'dijital pazarlama hizmetleri',
    'dijital pazarlama stratejisi',
    'dijital pazarlama çözümleri',
    'dijital pazarlama kampanyaları',
    'dijital pazarlama yönetimi',
    'dijital pazarlama planlama',
    'dijital pazarlama analizi',
    'dijital pazarlama optimizasyonu',
    'dijital pazarlama eğitimi',
    'dijital pazarlama danışmanlığı',
    'dijital pazarlama hizmeti',
    'dijital pazarlama destek',
    'dijital pazarlama çalışmaları',
    'dijital pazarlama projeleri',
    'dijital pazarlama firması',
    'dijital pazarlama şirketi',
    'profesyonel dijital pazarlama',
    'kurumsal dijital pazarlama',
    'B2B dijital pazarlama',
    'B2C dijital pazarlama',
    'e-ticaret dijital pazarlama',
    'online pazarlama',
    'internet pazarlama',
    'web pazarlama',
    'sosyal medya pazarlama',
    'içerik pazarlama',
    'video pazarlama',
    'mobil pazarlama',
    'email pazarlama',
    'influencer pazarlama',
    'affiliate pazarlama',
    'performance marketing',
    'growth marketing',
    'inbound marketing',
    'outbound marketing',
    'marketing automation',
    'dijital reklam',
    'online reklam',
    'internet reklamcılığı',
  ],
  
  socialMedia: [
    'sosyal medya yönetimi',
    'sosyal medya danışmanlığı',
    'sosyal medya stratejisi',
    'sosyal medya içerik',
    'sosyal medya planlama',
    'sosyal medya analizi',
    'sosyal medya optimizasyonu',
    'sosyal medya kampanyaları',
    'Instagram yönetimi',
    'Facebook yönetimi',
    'Twitter yönetimi',
    'LinkedIn yönetimi',
    'TikTok yönetimi',
    'YouTube yönetimi',
    'Pinterest yönetimi',
    'sosyal medya reklam',
    'Instagram reklam',
    'Facebook reklam',
    'LinkedIn reklam',
    'TikTok reklam',
    'sosyal medya içerik üretimi',
    'sosyal medya görsel tasarım',
    'sosyal medya video',
    'sosyal medya hikaye',
    'sosyal medya reels',
    'sosyal medya post',
    'sosyal medya story',
    'sosyal medya carousel',
    'sosyal medya infographic',
    'sosyal medya meme',
    'sosyal medya GIF',
    'sosyal medya animasyon',
    'sosyal medya engagement',
    'sosyal medya takipçi',
    'sosyal medya etkileşim',
    'sosyal medya büyüme',
    'sosyal medya community',
    'sosyal medya influencer',
  ],
  
  seo: [
    'SEO',
    'SEO uzmanı',
    'SEO danışmanı',
    'SEO hizmeti',
    'SEO çalışması',
    'SEO optimizasyonu',
    'SEO analizi',
    'SEO stratejisi',
    'Google SEO',
    'Yandex SEO',
    'Bing SEO',
    'arama motoru optimizasyonu',
    'arama motoru sıralaması',
    'Google sıralama',
    'organik trafik',
    'anahtar kelime araştırması',
    'keyword research',
    'on-page SEO',
    'off-page SEO',
    'technical SEO',
    'local SEO',
    'yerel SEO',
    'mobil SEO',
    'e-ticaret SEO',
    'içerik SEO',
    'blog SEO',
    'video SEO',
    'görsel SEO',
    'link building',
    'backlink',
    'site haritası',
    'robots.txt',
    'meta description',
    'title tag',
    'heading tags',
    'schema markup',
    'structured data',
    'rich snippets',
    'featured snippets',
    'Google My Business',
    'Google Analytics',
    'Google Search Console',
    'SEO audit',
    'SEO rapor',
    'SEO ölçümleme',
    'SEO takip',
  ],
  
  googleAds: [
    'Google Ads',
    'Google Ads uzmanı',
    'Google Ads danışmanı',
    'Google Ads yönetimi',
    'Google Ads kampanya',
    'Google Ads optimizasyonu',
    'Google AdWords',
    'PPC',
    'pay per click',
    'tıklama başı ödeme',
    'Google reklam',
    'Google reklamcılık',
    'arama ağı reklamları',
    'görüntülü reklam ağı',
    'Google Shopping',
    'ürün listeleme reklamları',
    'video reklamları',
    'YouTube reklamları',
    'display reklamları',
    'remarketing',
    'retargeting',
    'Google Analytics entegrasyonu',
    'dönüşüm takibi',
    'reklam bütçesi yönetimi',
    'reklam metni yazımı',
    'anahtar kelime teklifi',
    'kalite skoru',
    'reklam uzantıları',
    'dinamik arama reklamları',
    'responsive reklamlar',
    'akıllı kampanyalar',
    'performance max',
    'discovery reklamlar',
    'Gmail reklamları',
  ],
  
  metaBusiness: [
    'Meta Business',
    'Meta Business Suite',
    'Facebook Business',
    'Instagram Business',
    'Facebook reklam yönetimi',
    'Instagram reklam yönetimi',
    'Meta Ads',
    'Facebook Ads',
    'Instagram Ads',
    'Meta pixel',
    'Facebook pixel',
    'katalog yönetimi',
    'ürün akışı',
    'dinamik ürün reklamları',
    'carousel reklamlar',
    'collection reklamlar',
    'instant experience',
    'lead generation',
    'messenger reklamları',
    'WhatsApp Business',
    'Meta conversions API',
    'audience network',
    'hedef kitle oluşturma',
    'lookalike audience',
    'custom audience',
    'Meta Business Manager',
    'reklam hesabı yönetimi',
  ],
  
  webDesign: [
    'web tasarım',
    'web tasarımı',
    'web site tasarım',
    'web sitesi tasarımı',
    'kurumsal web tasarım',
    'profesyonel web tasarım',
    'responsive web tasarım',
    'mobil uyumlu web tasarım',
    'modern web tasarım',
    'özel web tasarım',
    'yaratıcı web tasarım',
    'UI tasarım',
    'UX tasarım',
    'kullanıcı deneyimi',
    'arayüz tasarımı',
    'web arayüz',
    'landing page',
    'iniş sayfası',
    'satış sayfası',
    'ürün sayfası',
    'hizmet sayfası',
    'portfolyo sitesi',
    'katalog sitesi',
    'tanıtım sitesi',
    'kurumsal site',
    'kişisel web sitesi',
    'blog tasarımı',
    'web portal',
    'web platformu',
    'figma tasarım',
    'adobe xd tasarım',
    'sketch tasarım',
    'wireframe',
    'mockup',
    'prototype',
  ],
  
  webDevelopment: [
    'web yazılım',
    'web geliştirme',
    'frontend geliştirme',
    'backend geliştirme',
    'fullstack geliştirme',
    'React',
    'Next.js',
    'Vue.js',
    'Angular',
    'Node.js',
    'JavaScript',
    'TypeScript',
    'HTML5',
    'CSS3',
    'Tailwind CSS',
    'Bootstrap',
    'API geliştirme',
    'RESTful API',
    'GraphQL',
    'database tasarım',
    'MySQL',
    'PostgreSQL',
    'MongoDB',
    'web uygulama',
    'progressive web app',
    'PWA',
    'single page application',
    'SPA',
    'server side rendering',
    'SSR',
    'static site generation',
    'SSG',
  ],
  
  wordpress: [
    'WordPress',
    'WordPress tasarım',
    'WordPress geliştirme',
    'WordPress tema',
    'WordPress özelleştirme',
    'WordPress eklenti',
    'WordPress site',
    'WordPress kurulum',
    'WordPress bakım',
    'WordPress güncelleme',
    'WordPress güvenlik',
    'WordPress optimizasyon',
    'WordPress hız',
    'WordPress SEO',
    'WooCommerce',
    'WooCommerce kurulum',
    'WooCommerce tasarım',
    'WordPress e-ticaret',
    'WordPress blog',
    'WordPress kurumsal',
    'WordPress portfolio',
    'Elementor',
    'WPBakery',
    'Divi',
    'Gutenberg',
    'WordPress yönetimi',
  ],
  
  ecommerce: [
    'e-ticaret',
    'e-ticaret sitesi',
    'online mağaza',
    'internet mağazası',
    'e-ticaret çözümleri',
    'e-ticaret yazılımı',
    'e-ticaret tasarım',
    'e-ticaret geliştirme',
    'e-ticaret yönetimi',
    'e-ticaret danışmanlığı',
    'e-ticaret SEO',
    'e-ticaret reklam',
    'e-ticaret pazarlama',
    'ürün yönetimi',
    'stok yönetimi',
    'sipariş yönetimi',
    'ödeme sistemi',
    'kargo entegrasyonu',
    'pazaryeri entegrasyonu',
    'Trendyol entegrasyonu',
    'Hepsiburada entegrasyonu',
    'N11 entegrasyonu',
    'Amazon entegrasyonu',
    'e-ihracat',
    'cross-border e-ticaret',
  ],
  
  digitalTransformation: [
    'dijital dönüşüm',
    'dijital dönüşüm danışmanlığı',
    'dijital dönüşüm stratejisi',
    'dijital dönüşüm projesi',
    'dijital transformasyon',
    'kurumsal dijitalleşme',
    'iş süreçleri dijitalleşme',
    'dijital inovasyon',
    'teknoloji entegrasyonu',
    'otomasyon çözümleri',
    'yapay zeka entegrasyonu',
    'chatbot entegrasyonu',
    'CRM sistemi',
    'ERP sistemi',
    'bulut çözümleri',
    'cloud solutions',
    'dijital iş modeli',
    'dijital strateji',
  ],
  
  branding: [
    'marka kimliği',
    'marka tasarımı',
    'logo tasarım',
    'kurumsal kimlik',
    'brand identity',
    'marka stratejisi',
    'marka yönetimi',
    'marka danışmanlığı',
    'görsel kimlik',
    'grafik tasarım',
    'kreativ tasarım',
    'reklam tasarımı',
    'katalog tasarımı',
    'broşür tasarımı',
    'kartvizit tasarımı',
    'antetli kağıt',
    'zarf tasarımı',
    'billboard tasarım',
    'afiş tasarım',
    'banner tasarım',
    'sosyal medya grafiği',
    'infographic tasarım',
    'sunum tasarımı',
    'powerpoint tasarım',
    'ambalaj tasarımı',
    'etiket tasarımı',
  ],
  
  contentCreation: [
    'içerik üretimi',
    'içerik yazımı',
    'blog yazısı',
    'makale yazımı',
    'SEO içerik',
    'web içerik',
    'ürün açıklaması',
    'kategori açıklaması',
    'haber yazısı',
    'basın bülteni',
    'sosyal medya içeriği',
    'video içerik',
    'podcast içerik',
    'e-kitap yazımı',
    'whitepaper',
    'case study',
    'başarı hikayesi',
    'müşteri yorumu',
    'referans yazısı',
    'email içeriği',
    'newsletter',
    'copywriting',
    'reklam metni',
    'slogan yazımı',
    'içerik stratejisi',
    'içerik takvimi',
    'içerik planlama',
  ],
  
  analytics: [
    'web analitik',
    'veri analizi',
    'Google Analytics',
    'Google Tag Manager',
    'Facebook Analytics',
    'Instagram Insights',
    'veri görselleştirme',
    'dashboard oluşturma',
    'rapor hazırlama',
    'performans analizi',
    'kullanıcı davranışı',
    'dönüşüm analizi',
    'trafik analizi',
    'heatmap',
    'A/B test',
    'conversion rate optimization',
    'CRO',
    'funnel analizi',
    'cohort analizi',
    'customer journey',
    'attribution modeling',
    'ROI analizi',
    'KPI takibi',
    'metrik ölçümleme',
  ],
  
  emailMarketing: [
    'email marketing',
    'email pazarlama',
    'e-posta pazarlama',
    'newsletter',
    'bülten gönderimi',
    'email kampanya',
    'email tasarım',
    'email otomasyon',
    'email segmentasyon',
    'email personalization',
    'drip kampanya',
    'welcome email',
    'abandoned cart email',
    're-engagement email',
    'email list büyütme',
    'email deliverability',
    'spam skoru',
    'email analytics',
    'açılma oranı',
    'tıklama oranı',
    'Mailchimp',
    'SendGrid',
    'GetResponse',
    'ActiveCampaign',
  ],
  
  videoMarketing: [
    'video pazarlama',
    'video içerik üretimi',
    'video çekim',
    'video montaj',
    'video düzenleme',
    'tanıtım filmi',
    'reklam filmi',
    'ürün videosu',
    'hizmet videosu',
    'kurumsal video',
    'animasyon video',
    'motion graphics',
    'explainer video',
    'tutorial video',
    'eğitim videosu',
    'webinar',
    'canlı yayın',
    'live streaming',
    'YouTube optimizasyonu',
    'video SEO',
    'video reklam',
    'video stratejisi',
  ],
  
  localSEO: [
    'yerel SEO',
    'Google Haritalar',
    'Google Maps',
    'Google My Business optimizasyonu',
    'yerel arama',
    'mahalle pazarlama',
    'şehir SEO',
    'bölgesel pazarlama',
    'konum bazlı pazarlama',
    'yerel işletme pazarlama',
    'yerel müşteri kazanma',
    'harita kaydı',
    'işletme kaydı',
    'yerel direktörler',
    'yol tarifi optimizasyonu',
  ],
  
  consulting: [
    'dijital danışmanlık',
    'pazarlama danışmanlığı',
    'strateji danışmanlığı',
    'büyüme danışmanlığı',
    'iş geliştirme',
    'satış danışmanlığı',
    'müşteri kazanma',
    'lead generation',
    'potansiyel müşteri',
    'satış hunisi',
    'sales funnel',
    'customer acquisition',
    'müşteri edinme',
    'pazar araştırması',
    'rakip analizi',
    'SWOT analizi',
    'hedef kitle analizi',
    'persona oluşturma',
    'pazarlama planı',
    'iş planı',
    'büyüme stratejisi',
  ],
  
  mobile: [
    'mobil uygulama',
    'mobil app',
    'iOS uygulama',
    'Android uygulama',
    'React Native',
    'Flutter',
    'mobil tasarım',
    'mobil UX',
    'mobil optimizasyon',
    'mobil reklam',
    'mobil pazarlama',
    'app store optimization',
    'ASO',
    'uygulama mağazası',
    'Google Play',
    'App Store',
    'mobil analitik',
    'push notification',
    'in-app messaging',
  ],
  
  conversion: [
    'dönüşüm optimizasyonu',
    'conversion optimization',
    'satış artırma',
    'gelir artırma',
    'kar artırma',
    'ROI artırma',
    'ROAS artırma',
    'müşteri değeri artırma',
    'sepet değeri artırma',
    'terk edilmiş sepet',
    'checkout optimizasyonu',
    'ödeme sayfası optimizasyonu',
    'landing page optimizasyonu',
    'CTA optimizasyonu',
    'form optimizasyonu',
    'kullanılabilirlik testi',
    'kullanıcı testi',
    'heatmap analizi',
    'session recording',
  ],
  
  automation: [
    'marketing automation',
    'pazarlama otomasyonu',
    'workflow automation',
    'iş akışı otomasyonu',
    'email automation',
    'social media automation',
    'chatbot',
    'AI chatbot',
    'müşteri hizmetleri otomasyonu',
    'CRM automation',
    'lead nurturing',
    'lead scoring',
    'drip campaign',
    'triggered email',
    'behavioral targeting',
    'personalization engine',
  ],
  
  cities: [
    'İstanbul dijital pazarlama',
    'Ankara dijital pazarlama',
    'İzmir dijital pazarlama',
    'Bursa dijital pazarlama',
    'Antalya dijital pazarlama',
    'Adana dijital pazarlama',
    'Konya dijital pazarlama',
    'Gaziantep dijital pazarlama',
    'Kocaeli dijital pazarlama',
    'Mersin dijital pazarlama',
    'online dijital pazarlama',
    'uzaktan dijital pazarlama',
    'freelance dijital pazarlama',
  ],
  
  industries: [
    'turizm dijital pazarlama',
    'otel dijital pazarlama',
    'restoran dijital pazarlama',
    'sağlık dijital pazarlama',
    'eğitim dijital pazarlama',
    'gayrimenkul dijital pazarlama',
    'otomotiv dijital pazarlama',
    'perakende dijital pazarlama',
    'finans dijital pazarlama',
    'sigorta dijital pazarlama',
    'teknoloji dijital pazarlama',
    'yapı dijital pazarlama',
    'mobilya dijital pazarlama',
    'tekstil dijital pazarlama',
    'kozmetik dijital pazarlama',
    'moda dijital pazarlama',
    'spor dijital pazarlama',
    'eğlence dijital pazarlama',
  ],
  
  services: [
    'dijital pazarlama hizmeti veren',
    'web tasarım hizmeti veren',
    'SEO hizmeti veren',
    'sosyal medya hizmeti veren',
    'profesyonel dijital hizmet',
    'kaliteli dijital hizmet',
    'uygun fiyatlı dijital hizmet',
    'güvenilir dijital hizmet',
    'deneyimli dijital pazarlamacı',
    'uzman dijital pazarlamacı',
    'sertifikalı dijital pazarlamacı',
    'Google Partner',
    'Meta Business Partner',
  ],
  
  longTail: [
    'dijital pazarlama nasıl yapılır',
    'web sitesi nasıl yapılır',
    'SEO nasıl yapılır',
    'Google Ads nasıl verilir',
    'Instagram reklamı nasıl verilir',
    'web sitesi fiyatları',
    'dijital pazarlama fiyatları',
    'SEO fiyatları',
    'sosyal medya yönetimi fiyatları',
    'en iyi dijital pazarlama',
    'en iyi web tasarım',
    'en iyi SEO uzmanı',
    'dijital pazarlama ajansı tavsiye',
    'web tasarımcı tavsiye',
    'SEO uzmanı tavsiye',
    'dijital pazarlama önerileri',
    'web tasarım önerileri',
    'SEO önerileri',
  ],
}

// Tüm kelimeleri birleştir
export function getAllKeywords(): string {
  const allKeywords: string[] = []
  Object.values(seoKeywords).forEach(category => {
    allKeywords.push(...category)
  })
  return allKeywords.join(', ')
}

// Kategori bazlı kelimeler
export function getKeywordsByCategory(categories: string[]): string {
  const keywords: string[] = []
  categories.forEach(cat => {
    if (seoKeywords[cat as keyof typeof seoKeywords]) {
      keywords.push(...seoKeywords[cat as keyof typeof seoKeywords])
    }
  })
  return keywords.join(', ')
}
